/**
 * Typed contract for the search-intelligence Edge Function
 * (supabase/functions/search-intelligence/). Keep this in sync with that
 * function's request/response shapes by hand — it's Deno code in a separate
 * runtime, so it can't literally import this file.
 */

export type SearchIntent =
  | "exact_product" | "product_family" | "ingredient" | "category"
  | "symptom_need" | "attribute_request" | "alternative_product"
  | "similar_product" | "brand_request" | "price_request"
  | "availability_request" | "broad_discovery" | "recent_product"
  | "unclear_query";

export interface SearchIntelligenceRequest {
  query: string;
  category?: string | null;
  inStock?: boolean;
  limit?: number;
  recentQueries?: string[];
}

/** Same row shape as search_effective_products — see EffectiveProductRow in
 *  ../types/index.ts. Left loosely typed here since the Edge Function forwards
 *  the RPC's rows verbatim; callers should re-validate with
 *  EffectiveProductRowSchema before treating a field as trustworthy. */
export type SearchIntelligenceProductRow = Record<string, unknown>;

export interface SearchIntelligenceResponse {
  intent: SearchIntent;
  intentSource: "rule";
  products: SearchIntelligenceProductRow[];
  totalCount: number;
  /** A short deterministic Arabic template sentence keyed by intent — not
   *  generated by a model. This system calls no external AI API. */
  aiExplanation: string | null;
  /** Always null — kept only for response-shape stability. */
  aiConfidence: number | null;
  clarificationQuestion: string | null;
  /** "supabase-embeddings" when the Supabase-native gte-small semantic
   *  supplement contributed extra rows; "none" otherwise. Never a third-party
   *  provider name — there isn't one. */
  provider: "none" | "supabase-embeddings";
}
